name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.6

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to server
        run: mvn clean package

